### ISSUE TITLE
Towards v0.1

### ISSUE THREAD

**Issue by retro** [retro/generator-canjs#11]
I'm thinking about v0.1, and what should be done before it. So on my current list is this:
- [x] Decouple fixture generator from model
- [x] Investigate https://github.com/marak/Faker.js/ to see if we can create better fixture generator with it 
- [ ] Add scaffold generator - which could create model, list and form controls, etc.
- [ ] Stop generating both `.ejs` and `.mustache` views
- [x] Add server task to the `Gruntfile.js`

Any suggestions are welcome

**Comment by frank-dspeed** [comment]
@dubilla @cherifGsoul @retro 

we will solve the server parts via steal-server
