### ISSUE TITLE
CanJS typical app structure

### ISSUE THREAD

**Issue by cherifGsoul** [retro/generator-canjs#18]
I want to open a talk for the best structure for a large app or a project for canjs to be implemented and generated by generator-canjs so here some points:
1- Start a project
2- Project has many apps
3- apps are grouped by feature (email app, contact app, tasks app ... etc)
4- each app has folders with controls, components, templates and why not herlpers (mustache/EJS helpers).
5- Models can be shared so models folder will belong to the whole project

your thoughts and comments are welcome

**Comment by frank-dspeed** [comment]
@retro @cherifGsoul i will close that as this is solved via the components feature at present
